### ISSUE TITLE
Moderation tools

### ISSUE THREAD

**Issue by SamR1** [SamR1/FitTrackee#382]
Users can report:
- comments,
- workouts,
- users.

On report creation, a notification is sent to all users with moderation rights.

Possible actions following a report:
- sent an email to the reported user
- _suspend_ the comment or workout of the reported user
- suspend the reported user's account.

A suspended user can log in, but access will be limited (export request and account deletion are possible).
A suspended user can appeal the suspension.

---

**TODO**:
 - [x] reports management  
   - [x] report creation on comment, workout and user
   - [x] mark report as (un-)resolved
   - store reported object (since it can be updated) ? => in a next version
 - [x] report actions
   - [x] suspend a user account
   - [x] _suspend_ workout
   - [x] _suspend_ comment
   - [x] user warning
 - [x] report actions logs
   - [x] report status update
   - [x] on user (un-)suspension 
   - [x] on workout _(un-)suspension_
   - [x] on comment _(un-)suspension_
   - [x] on user warning  
 - [x] UI notifications
   - [x] report creation for moderator
   - [x] user warning
   - [x] workout _suspension_
   - [x] comment _suspension_
   - [x] appeals for moderator
 - [x] mail notifications
   - [x] user warning
   - [x] account suspension 
   - [x] workout _suspension_
   - [x] comment _suspension_
   - [x] rejected appeal
 - [x] handle suspended user 
   - [x] limited access for suspended user
     - [x] notifications from suspended user are not displayed
     - [x] sports, apps and equipments can not be modified
   - [x] suspended user display
     - [x] suspended user workouts and comments should not be visible 
     - [x] suspended user is not visible in user directory
- [x] handle suspended content
  - [x] suspended workout   
  - [x] suspended comment   
- [x] allow user to appeal suspensions
   - [x] account suspension 
   - [x] workout _suspension_
   - [x] comment _suspension_
   - [x] user warning
- [x] display user sanctions
  - [x] for moderator
  - [x] for user

**Comment by SamR1** [comment]
released in v0.9.0b1
